# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.scraper:
      class: AppBundle\Utils\Scraper
      arguments: ['@doctrine.orm.entity_manager', '@service_container']
    app.twig_extension:
      class: AppBundle\Twig\AppExtension
      public: false
      tags:
        - { name: twig.extension }
    templating.engine.pug:
        class: Pug\PugSymfonyEngine
        arguments: ["@kernel"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
